routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'EmployeesController@index');

Route::resource('employees', EmployeesController::class);

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $fillable = [
        'name',
        'primary_mobile_number_id',
        'primary_whatsapp_number_id',
        'primary_email_id',
    ];

    // RELATIONSHIP METHODS
    public function address() {
        return $this->hasOne(Address::class, 'emp_id');
    }

    public function mobileNumbers() {
        return $this->hasMany(MobileNumber::class, 'emp_id');
    }

    public function whatsappNumbers() {
        return $this->hasMany(WhatsappNumber::class , 'emp_id');
    }

    public function emails() {
        return $this->hasMany(Email::class, 'emp_id');
    }

    // HELPER METHODS
    public function getPrimaryMobileNumber() {
        return $this->mobileNumbers
                    ->find($this->primary_mobile_number_id)
                    ->mobile_number;
    }

    public function getPrimaryWhatsappNumber() {
        return $this->whatsappNumbers
                    ->find($this->primary_whatsapp_number_id)
                    ->whatsapp_number;
    }

    public function getPrimaryEmail() {
        return $this->emails
                    ->find($this->primary_email_id)
                    ->email;
    }

    public function getAllPrimaryAttributes() {
        return $primaryAttributes = [
            'primary_mobile_number'     =>  $this->getPrimaryMobileNumber(),
            'primary_whatsapp_number'   =>  $this->getPrimaryWhatsappNumber(),
            'primary_email'             =>  $this->getPrimaryEmail(),
        ];
    }

    public function getAllMobileNumbers() {
        $mobile_numbers = $this->mobileNumbers
                                ->all();
                                
        $mobileNumbers = array();

        foreach($mobile_numbers as $mobile_number) {
            array_push($mobileNumbers, $mobile_number->mobile_number);
        }

        return $mobileNumbers;
    }

    public function getAllWhatsappNumbers() {
        $whatsapp_numbers = $this->whatsappNumbers
                                ->all();

        $whatsappNumbers = array();

        foreach($whatsapp_numbers as $whatsapp_number) {
            array_push($whatsappNumbers, $whatsapp_number->whatsapp_number);
        }

        return $whatsappNumbers;
    }

    public function getAllEmails() {
        $emails = $this->emails
                        ->all();

        $emailsArray = array();

        foreach($emails as $email) {
            array_push($emailsArray, $email->email);
        }

        return $emailsArray;
    }

    public function getMobileNumberModelFromNumber($mobile_number) {
        return $this->mobileNumbers()
            ->where(
                'mobile_number', 
                $mobile_number)
            ->first();
    }

    public function getWhatsappNumberModelFromNumber($whatsapp_number) {
        return $this->whatsappNumbers()
                    ->where('whatsapp_number', $whatsapp_number)
                    ->first();
    }

    public function getEmailModelFromEmail($email) {
        return $this->emails()
                    ->where('email', $email)
                    ->first();
    }

    public function getMobileNumberIdFromNumber($mobile_number) {
        return $this->mobileNumbers
                    ->where('mobile_number', $mobile_number)
                    ->first()
                    ->id;
    }

    public function getWhatsappNumberIdFromNumber($whatsapp_number) {
        return $this->whatsappNumbers
                    ->where('whatsapp_number', $whatsapp_number)
                    ->first()
                    ->id;
    }

    public function getEmailIdFromEmail($email) {
        return $this->emails
                    ->where('email', $email)
                    ->first()
                    ->id;
    }
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Address;
use App\Email;
use App\Employee;
use App\MobileNumber;
use App\WhatsappNumber;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();
        return view('employees.index', compact([
            'employees'
        ])
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->input());

        $this->insertEmployee($request);

        return redirect(route('employees.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('employees.show', compact([
            'employee'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        return view('employees.edit', compact([
            'employee'
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $employee->update([
            'name'  =>  $request->name
        ]);

        $address_data = $request->only([
            'address_line_1',
            'address_line_2',
            'location',
            'zip_code',
            'postal_area',
            'taluka',
            'suburb',
            'east_west',
            'city',
            'district',
            'state',
            'country',
        ]);

        $existing_address_attributes = $employee->address->getAttributes();
        $address_diff = array_diff_assoc($address_data, $existing_address_attributes);

        $employee->address()
                ->update($address_diff);

        
        /**
         * STEPS TO UPDATE MOBILE NUMBERS:
         * 
         * Check if the existing mobile number is present in the requested mobile number array
         * If yes, remove that number from the existing mobile number array and requested mobile number array
         * If not, replace the existing number with the requested mobile number and remove existing mobile number and requested mobile number from their arrays respectively 
         * Repeat this until the existing mobile number array and requested mobile number array is not empty
         * If existing mobile number array is empty, insert the remaining requested mobile numbers
         * If requested mobile number array is empty, delete the remaining existing mobile numbers
         */
        
        // Code to update mobile numbers
        $existing_mobile_numbers = $employee->getAllMobileNumbers();
        $requested_mobile_numbers = $request->mobile_numbers;

        // dd($existing_mobile_numbers, $requested_mobile_numbers);

        while($existing_mobile_numbers && $requested_mobile_numbers) {
            
            $indexOfRequest = array_search($existing_mobile_numbers[0], $requested_mobile_numbers);

            if($indexOfRequest !==  false) {
                
                if($existing_mobile_numbers[0] == $request->primary_mobile_number) {
                    $mobile_number_id = $employee->getMobileNumberIdFromNumber($existing_mobile_numbers[0]);
                    $this->updatePrimaryMobileNumberId($employee, $mobile_number_id);
                }

                array_splice($existing_mobile_numbers, 0, 1);
                array_splice($requested_mobile_numbers, $indexOfRequest, 1);

            } else {

                $mobile_number = $employee->getMobileNumberModelFromNumber($existing_mobile_numbers[0]);
                
                $mobile_number->update([
                    'mobile_number' =>  $requested_mobile_numbers[0]
                ]);

                if($requested_mobile_numbers[0] == $request->primary_mobile_number) {
                    // dd("UPDATING");
                    $this->updatePrimaryMobileNumberId($employee, $mobile_number->id);
                }

                array_splice($existing_mobile_numbers, 0, 1);
                array_splice($requested_mobile_numbers, 0, 1);
            }
        }
        
        if(!$existing_mobile_numbers) {
            // dd("Existing Number Array is empty");

            foreach($requested_mobile_numbers as $requested_mobile_number) {

                $mobile_number = MobileNumber::create([
                    'emp_id'        =>  $employee->id,
                    'mobile_number' =>  $requested_mobile_number
                ]);

                if($requested_mobile_number == $request->primary_mobile_number) {
                    $this->updatePrimaryMobileNumberId($employee, $mobile_number->id);
                }
            }
        }
    
        if(!$requested_mobile_numbers) {
            // dd("Requested Number Array is empty");

            foreach($existing_mobile_numbers as $existing_mobile_number) {

                $mobile_number = $employee->getMobileNumberModelFromNumber($existing_mobile_number);
                $mobile_number->delete();
            }
        }
        
        /*
         * ALTERNATIVE WAY
         * Delete the existing mobile numbers
         * Add mobile numbers
         */

        // $employee->mobileNumbers()->delete();

        // foreach($request->mobile_numbers as $mobile_number) {
        //     $mobileNumber = MobileNumber::create([
        //         'emp_id'        =>  $employee->id,
        //         'mobile_number' =>  $mobile_number,
        //     ]);
        //     if($mobileNumber->mobile_number == $request->primary_mobile_number) {
        //         $primary_mobile_number_id = $mobileNumber->id;
        //     }
        // }

        // Code to update whatsapp numbers
        $existing_whatsapp_numbers = $employee->getAllWhatsappNumbers();
        $requested_whatsapp_numbers = $request->whatsapp_numbers;

        while($existing_whatsapp_numbers && $requested_whatsapp_numbers) {
            
            $indexOfRequest = array_search($existing_whatsapp_numbers[0], $requested_whatsapp_numbers);

            if($indexOfRequest !== false) {

                if($existing_whatsapp_numbers[0] == $request->primary_whatsapp_number) {
                    $whatsapp_number_id = $employee->getWhatsappNumberIdFromNumber($existing_whatsapp_numbers[0]);
                    $this->updatePrimaryWhatsappNumberId($employee, $whatsapp_number_id);
                }

                array_splice($existing_whatsapp_numbers, 0, 1);
                array_splice($requested_whatsapp_numbers, $indexOfRequest, 1);

            } else {

                $whatsapp_number = $employee->getWhatsappNumberModelFromNumber($existing_whatsapp_numbers[0]);
                
                $whatsapp_number->update([
                    'whatsapp_number' =>  $requested_whatsapp_numbers[0]
                ]);

                if($requested_whatsapp_numbers[0] == $request->primary_whatsapp_number) {
                    $this->updatePrimaryWhatsappNumberId($employee, $whatsapp_number->id);
                }

                array_splice($existing_whatsapp_numbers, 0, 1);
                array_splice($requested_whatsapp_numbers, 0, 1);
            }
        }

        if(!$existing_whatsapp_numbers) {

            foreach($requested_whatsapp_numbers as $requested_whatsapp_number) {

                $whatsapp_number = WhatsappNumber::create([
                    'emp_id'            =>  $employee->id,
                    'whatsapp_number'   =>  $requested_whatsapp_number
                ]);

                if($requested_whatsapp_number == $request->primary_whatsapp_number) {
                    $this->updatePrimaryWhatsappNumberId($employee, $whatsapp_number->id);
                }
            }
        }

        if(!$requested_whatsapp_numbers) {
            foreach($existing_whatsapp_numbers as $existing_whatsapp_number) {
                $whatsapp_number = $employee->getWhatsappNumberModelFromNumber($existing_whatsapp_number);
                $whatsapp_number->delete();
            }
        }

        // Code to update emails
        $existing_emails = $employee->getAllEmails();
        $requested_emails = $request->emails;

        while($existing_emails && $requested_emails) {
            
            $indexOfRequest = array_search($existing_emails[0], $requested_emails);

            if($indexOfRequest !== false) {

                if($existing_emails[0] == $request->primary_email) {
                    $email_id = $employee->getEmailIdFromEmail($existing_emails[0]);
                    $this->updatePrimaryEmailId($employee, $email_id);
                }

                array_splice($existing_emails, 0, 1);
                array_splice($requested_emails, $indexOfRequest, 1);

            } else {

                $email = $employee->getEmailModelFromEmail($existing_emails[0]);
                
                $email->update([
                    'email' =>  $requested_emails[0]
                ]);

                if($requested_emails[0] == $request->primary_email) {
                    $this->updatePrimaryEmailId($employee, $email->id);
                }

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">
        <h3 class="mb-4">Create Employee</h3>
        <div id="emp_details_container">
            <h5>Employee Details</h5>
            <form id="emp_details_form" class="needs-validations" action="{{ route('employees.store') }}" method="POST" novalidate>
                @csrf

                {{-- START: EMPLOYEE DETAILS --}}
                <div class="row mb-5">
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="name" class="d-flex">Employee Name</label>
                            <input id="name" class="form-control" type="text" placeholder="Enter your name" name="name">
                        </div>
                    </div>
                </div>
                {{-- END: EMPLOYEE DETAILS --}}

                {{-- START: ADDRESS DETAILS --}}
                <h6>Address Details</h6>
                <div class="row mb-3">
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="address_line_1" class="d-flex">Address 1 *</label>
                            <input id="address_line_1" class="form-control" type="text" placeholder="Address 1" name="address_line_1" required>
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="address_line_2" class="d-flex">Address 2</label>
                            <input id="address_line_2" class="form-control" type="text" name="address_line_2" placeholder="Address 2">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="location" class="d-flex">Location</label>
                            <input id="location" class="form-control" type="text" name="location" placeholder="Location">
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="zip_code"  class="d-flex">Zip / Postal Code</label>
                            <input id="zip_code" class="form-control" name="zip_code" type="text" placeholder="Zip / Postal Code">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="postal_area" class="d-flex">Postal Area</label>
                            <input id="postal_area" class="form-control" name="postal_area" type="text" placeholder="Postal Area">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <label for="taluka" class="d-flex">Taluka</label>
                        <input id="taluka" class="form-control" name="taluka" type="text" placeholder="Taluka">
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="suburb" class="d-flex">Suburb</label>
                            <input id="suburb" class="form-control" name="suburb" type="text" placeholder="Suburb">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="east_west" class="d-flex">East / West</label>
                            <input id="east_west" class="form-control" name="east_west" type="text" placeholder="East / West">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="city" class="d-flex">City *</label>
                            <input id="city" class="form-control" name="city" type="text" placeholder="City" required>
                        </div>
                    </div>
                </div>

                <div class="row mb-5">
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="district" class="d-flex">District</label>
                            <input id="district" class="form-control" name="district" type="text" placeholder="District">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="state" class="d-flex">State</label>
                            <input id="state" class="form-control" name="state" type="text" placeholder="State">
                        </div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-3">
                        <div class="form-group m-0">
                            <label for="country" class="d-flex">Country</label>
                            <input id="country" class="form-control" name="country" type="text" placeholder="Country" required>
                        </div>
                    </div>
                </div>
                {{-- END: ADDRESS DETAILS --}}

                {{-- START: CONTACT DETAILS --}}
                <h6>Contact Details</h6>
                <div class="row mb-3">
                    <div class="col-md-4">
                        <label class="mr-4">Mobile Number</label>
                        <div id="btn_add_mobile_number_field" type="button" 
                        class="btn btn-small btn-outline-success mb-3">
                            <i>+</i>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label for="" class="m-0">Mobile Number</label>
                            </div>
                        </div>
                        <ul id="mobile_number_list" class="list-group list-unstyled" >
                            <li id="" class="list-item">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input id="mobile_number_1" name="mobile_numbers[]" class="mt-2 mb-4 mr-2 form-control w-50 d-inline-block" type="text" placeholder="0000000000">
                                        <input type="radio" class="primary_mobile_number" id="primary_mobile_number_1" name="primary_mobile_number_status" checked>
                                        <label for="" class="m-0">Primary</label>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <label class="mr-4">Whatsapp Number</label>
                        <div id="btn_add_whatsapp_number_field" type="button" 
                        class="btn btn-small btn-outline-success mb-3">
                            <i>+</i>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label for="" class="m-0">Whatsapp Number</label>
                            </div>
                        </div>
                        <ul id="whatsapp_number_list" class="list-group list-unstyled" >
                            <li id="" class="list-item">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input id="whatsapp_number_1" name="whatsapp_numbers[]" class="mt-2 mb-4 mr-2 form-control w-50 d-inline-block" type="text" placeholder="0000000000">
                                        <input type="radio" id="primary_whatsapp_number_1" name="primary_whatsapp_number_status" checked>
                                        <label for="" class="m-0">Primary</label>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <label class="mr-4">Email</label>
                        <div id="btn_add_email_field" type="button" 
                        class="btn btn-small btn-outline-success mb-3">
                            <i>+</i>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <label for="" class="m-0">Email *</label>
                            </div>
                        </div>
                        <ul id="email_list" class="list-group list-unstyled" >
                            <li id="" class="list-item">
                                <div class="row">
                                    <div class="col-md-12">
                                        <input id="email_1" name="emails[]" class="mt-2 mb-4 mr-2 form-control w-50 d-inline-block" type="text" placeholder="123@example.com">
                                        <input type="radio" id="primary_email_1" name="primary_email_status" checked>
                                        <label for="" class="m-0">Primary</label>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                {{-- END: CONTACT DETAILS --}}

                {{-- START: HIDDEN FIELDS --}}
                <input type="hidden" id="primary_mobile_number" name="primary_mobile_number">

                <input type="hidden" id="primary_whatsapp_number" name="primary_whatsapp_number">

                <input type="hidden" id="primary_email" name="primary_email">
                {{-- END: HIDDEN FIELDS --}}

                {{-- START: NAVIGATIONS --}}
                <a href="{{route('employees.index')}}" class="btn btn-primary d-inline-block mr-3">Back</a>

                <button type="submit" class="btn btn-success">Submit</button>
                {{-- END: NAVIGATIONS --}}

            </form>
        </div>
    </div>

@endsection

@section('scripts')
    <script src="https://code.jquery.com/git/jquery-git.min.js"></script>
    <script src="{{ asset('js/create.js') }}"></script>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
@endsection

@section('content')
    <div class="container p-3">
        <h5 class="mb-4">Employee Details</h5>
        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <a href="{{route('employees.create')}}" class="btn btn-primary d-inline-block mb-3 float-right">
                    <i class="fa fa-plus"> Create Employee</i>
                </a>
            </div>
        </div>
        <table id="employee_datatable" class="table table-striped table-bordered text-center" style="width:100%">
            <thead>
                <tr>
                    <th>Sr No.</th>
                    <th>Name</th>
                    <th>Operations</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($employees as $employee)
                    <tr>
                        <td></td>
                        <td>{{ $employee->name }}</td>
                        <td>
                            <a href="{{route('employees.show', $employee->id)}}" class="btn btn-outline-secondary mr-2"><i class="fa fa-eye" aria-hidden="true"></i></a>
                            <a href="{{route('employees.edit', $employee->id)}}" class="btn btn-outline-primary mr-2"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                            <form class="d-inline" action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" 
                                onclick="return confirm('Are you sure you want to delete ?');" 
                                class="btn btn-outline-danger">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <th>Sr No.</th>
                    <th>Name</th>
                    <th>Operations</th>
                </tr>
            </tfoot>
        </table>
    </div>

@endsection

@section('scripts')
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('js/index.js') }}"></script>
@endsection